#! /bin/bash
diskutil erasevolume HFS+ "ramdisk" `hdiutil attach -nomount ram://1165430`
cp -r Video/TARGA /volumes/ramdisk/TARGA
cp -r images /volumes/ramdisk/images
cp -r Audio /volumes/ramdisk/audio
